markdown: kramdown
permalink: /blog/:title/
gems: [jekyll-paginate]
paginate: 9
paginate_path: /blog/page:num
highlighter: rouge

exclude: ["node_modules", "src", "gulpfile.js", "package.json", "nqstnet.sublime-project", "nqstnet.sublime-workspace"]